version: '3.4'

services:
  st-dotnet:
    image: ${DOCKER_REGISTRY-}stdotnet
    build:
      context: .
      dockerfile: st-dotnet/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GalleryMySql__Conn=server=db; database=GALLERY; user=; password=
      - S3__AccessKeyId=
      - S3__SecretKey=
    ports:
      - "8086:80"
      - "443:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=GALLERY
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
    hostname: db
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
